### ISSUE TITLE
Continuous Overline on Port Names

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#114]
When using the 'inverted' syntax in Port Names (e.g. "!(LOAD A)") the Overline (bar) on the produced label is not continuous. It would be great if the line would be uninterrupted and fitting to the char width of the respective char. 

![image](https://user-images.githubusercontent.com/25486087/119154591-97b15d00-ba52-11eb-92e1-b5cfb9115105.png)

**Comment by flandreas** [comment]
Yeah, that looks ugly indeed. The feature is currently implemented using special unicode characters that produce the overline, and as far as I understand, the width of the overline depends on the font actually being used. I will look around to see if I can find a better solution for this problem.

**Comment by Kitick** [comment]
Well actually one solution is to use HTML. Antares's UI is coded in HTML correct? So really all you'd need to do is set the style of the label to add the overline. I don't remember the specific code however I do remember it exists.

**Comment by flandreas** [comment]
Well, Antares' UI is coded in Java using the Swing framework, but some parts like the multiline text is drawn using a particular Swing component that can draw HTML text. But as far as I know, this HTML rendering component does not have great CSS support, if any at all. And the port labels are currently not drawn using HTML.

I was also thinking about a compromise solution: If the entire text is inverted, then the overline could be drawn programmatically just by "draw line", because the size box of the entire text is known at that moment.

**Comment by flandreas** [comment]
Implemented the compromise solution: Draw the overline programmatically if the entire text is negated. Currently only applied to pin labels and other component labels, but that's the most important usage anyway.

<img width="362" alt="overline" src="https://user-images.githubusercontent.com/24633141/119682545-41be2a00-be43-11eb-81d1-5275a5ab03f2.png">

The solution can be extended later, especially when it comes to other text decorations or things like subscripts.
