### ISSUE TITLE
Application Hangs due to wiring algo going wild

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#143]
Given: 
![image](https://user-images.githubusercontent.com/25486087/120509997-4cd80380-c3c9-11eb-817a-ab60a6d1bfc4.png)

Move lower transistor up: 
![image](https://user-images.githubusercontent.com/25486087/120510074-5cefe300-c3c9-11eb-8746-fa585eed23c3.png)

Try to move it back down (or somewhere else) and the application will hang for several seconds while doing some rocket science math in the background.

**Comment by richardabendroth** [comment]
And refuses to close: 
![image](https://user-images.githubusercontent.com/25486087/120510699-f7502680-c3c9-11eb-91c8-940a19f1bf62.png)

**Comment by richardabendroth** [comment]
@flandreas can I help somehow to investigate this issue?

**Comment by flandreas** [comment]
@richardabendroth That's kind, thank you! I hadn't time to look into this one. I'm still stuck with #150, which turned out to be tougher than I hoped. It requires quite some changes in the start-up procedures of the simulation, and I have to be careful not to introduce regression problems. But alas, I hope that this one will be easier :-)

**Comment by flandreas** [comment]
Antares is suddenly starting to draw polylines with quite a lot of points, thereby eating up all your heap memory. Sorry for that :-)

2021-06-07 16:40:20,072 TRACE [AWT-EventQueue-0] (EdgeViewLineStyling.kt:30) - Draw polyline with 2 points
2021-06-07 16:40:20,072 TRACE [AWT-EventQueue-0] (EdgeViewLineStyling.kt:30) - Draw polyline with 262147 points

**Comment by richardabendroth** [comment]
That explains it 😅
