### ISSUE TITLE
Input not touchable

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#147]
In a complex shape, one of the symbol inputs cannot be connected to anything (does not show the yellow bubble when hovering). 
![image](https://user-images.githubusercontent.com/25486087/120614436-86efe680-c457-11eb-9305-6cb8656799cc.png)

**Comment by flandreas** [comment]
Interesting. I can reproduce it, but in my case, it is the pin pointing south that can not be connected.

**Comment by richardabendroth** [comment]
Maybe it depends on how you draw the shape or which of the pins you place first?

**Comment by flandreas** [comment]
Yeah, probably the order of placement. I'm investigating... :-)

**Comment by flandreas** [comment]
Found it. The algorithm looks for the pin with the minimum distance from the mouse location, and used the location of the pin as a reference instead of the connection point at the end of the pin line. You are probably the first to place two pins at the same location ;-)

Thank you for reporting this!

**Comment by richardabendroth** [comment]
You are welcome! I was learning about Transmission Gates which might be the only symbol out there where this case even appears 🙈
