### ISSUE TITLE
Rookie Question: Why does a pull-down resistor go Z when connected to Power?

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#149]
![image](https://user-images.githubusercontent.com/25486087/120626619-1fd82f00-c463-11eb-9594-437bf13f9342.png)

**Comment by flandreas** [comment]
The way how  pull resistors work (at least in my understanding) is that they pull a wire to the desired level if the wire carries an undefined signal. In all other cases, they remain passive, i.e. don't participate in asserting signals to the wire, i.e. are undefined.

But I am aware that this can look confusing. I've got an issue on my hidden agenda for thinking about whether the pull resistor should draw itself differently in this situation, e.g. using a color gradient from 1 (bright green) to 0 (dark green) in your scenario. What wouldn't work is to draw it in 0 (dark green) only, because you would then have an unexplainable clash of 0 and 1 at the pin where the resistor is connected to the wire.

**Comment by richardabendroth** [comment]
Ah, I see! Thank you for your explanation! That makes total sense!
