### ISSUE TITLE
Explorer Side Bar Width and Circuit Area Width not correctly restored  

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#164]
In Simulation Mode, wwitch to Window Mode: 
![image](https://user-images.githubusercontent.com/25486087/121377598-c2e8e700-c942-11eb-9f7e-aca5ac5df65b.png)

Hide Explorer: 
![image](https://user-images.githubusercontent.com/25486087/121377660-d005d600-c942-11eb-94ec-6b6c7bc492de.png)

Maximize Window: 
![image](https://user-images.githubusercontent.com/25486087/121377713-dd22c500-c942-11eb-857d-deb09bf26d74.png)

Re-open Explorer: 
![image](https://user-images.githubusercontent.com/25486087/121377786-eca20e00-c942-11eb-95ac-bf69a7154acd.png)

After manually Re-sizing the Explorer Side-Bar: 
![image](https://user-images.githubusercontent.com/25486087/121377901-05aabf00-c943-11eb-9e1e-301a83ebdd3c.png)

**Comment by flandreas** [comment]
I've seen this once a long time ago when I've built the first release on Windows.

One of the problems is that the tabs at the left and right borders ("Explorer", "Scenarios", "Issues") should be vertical instead of horizontal. Are they always horizontal in your installation, or just now, when the re-layout problem occurs? I've also seen these horizontal tabs once on Windows after I switched to another theme.

**Comment by richardabendroth** [comment]
I think always: 

![image](https://user-images.githubusercontent.com/25486087/121425593-e035a980-c972-11eb-8ecf-4f3f419f4420.png)
![image](https://user-images.githubusercontent.com/25486087/121425659-f3e11000-c972-11eb-8b72-4c197031d0b6.png)
