### ISSUE TITLE
Rotate entire selection

### ISSUE THREAD

**Issue by aquamiau** [flandreas/antares#285]
I find myself wanting to rotate entire selections occasionally, that would save some time rearranging circuits.

**Comment by aquamiau** [comment]
This also goes for mirroring

**Comment by flandreas** [comment]
Interesting feature, although probably not the easiest one to implement properly, especially because wires cannot be rotated yet. I'll think about it..

**Comment by flandreas** [comment]
Rotation implemented

**Comment by flandreas** [comment]
Mirroring would be much more difficult, because subcircuit symbol is currently the only component that can be mirrored. Mirroring entire selections would require to make all components like gates, switches, input/outputs etc mirrorable.

Let's see whether rotation by 180 degrees can cover most of your use cases. Otherwise, please open a separate feature request for mirroring.
