### ISSUE TITLE
Exporting ROM Content and reimporting doesnt work

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#297]
Exporting the ROM Content to a File works. But reimporting that exported File doesnt work.
Error Message: "The Import File cant be read."

**Comment by flandreas** [comment]
@leonuetzel Thank you for reporting this. Cannot reproduce. May I ask you to attach the exported file? And what are the characteristics of your ROM (address width, data width)?

**Comment by leonuetzel** [comment]
![ROM](https://user-images.githubusercontent.com/39810063/152142976-a9917e0d-c978-4b37-bdf6-80be362fb296.PNG)
This is the ROM Content: https://www.transfernow.net/dl/20220202nUirqx1J

**Comment by leonuetzel** [comment]
![error](https://user-images.githubusercontent.com/39810063/152143411-a6ed77c0-1b6d-4750-aa4e-9353500184e0.PNG)
And this is the Error. ROM is 64Kx8

**Comment by flandreas** [comment]
@leonuetzel Thank you! I'm still not able to reproduce the problem. On my test machines (Mac, Windows), I'm able to import your file without any problem.

The only thing I can imagine is that on machine the file lies at a location where Antares doesn't have enough privileges to read it. Although I suppose the file still lies at the location where Antares wrote it in the first place, so that would be strange as well.

Could you please repeat your test and then export the log file (using File -> Export Log File) and attach it here? I would expect to see some "No Access to File" exception in the log file.

**Comment by leonuetzel** [comment]
[Antares-log.zip](https://github.com/flandreas/antares/files/7986407/Antares-log.zip)

**Comment by flandreas** [comment]
Ok, it must be something else. I'm analyzing...

**Comment by flandreas** [comment]
It seems like the problem is caused by memory contents popup window that issues an undoable command when importing or clearing contents, but doesn't correctly behave upon resulting data changes.
