### ISSUE TITLE
Plugin for minimizing Boolean Algebra

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#319]
Hello,

it would be nice, if Antares had a Plugin/Add-On or some kind of tool to minimize Boolean Algebra that can be implemented then.
For example if one knows, what the circuit should do in dependence of the Inputs, but doesnt know the exact Transfer-Function, so the user simply fills the Truth-Table and the Plugin calculates the Boolean Function from it, which can be implemented then with Logic Gates.

**Comment by flandreas** [comment]
Good suggestion, but a large topic on its own, similar to #234.

Since there are already online web tools like http://tma.main.jp/logic/index_en.html that provide this functionality, we would probably start in Antares with parsing logical expression and generating circuits that represent these expression. Editing truth tables and doing minimization within Antares would then be the next step, along with creating expressions from existing circuits in Antares.

Surely on the long term, these are important features, but I would consider others as currently more pressing, such as #212 or the upcoming web version of Antares.
