### ISSUE TITLE
Fixed Point Qm.n Format Visualisation

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#411]
It would be nice if there would be a Probe to make Fixed-Point Formats readable.
So the User has to choose the Input-Bitwidth and has to set m and n and the Probe converts the hex-Value to a readable float-Value.

**Comment by flandreas** [comment]
@leonuetzel Interesting suggestion.

I guess it would be sufficient to only have "n" (fraction bit count) as additional property, because "m" would always be "input bit width - n".

For which "Representation" would you like to have this feature? Only for decimal representation, or also for the other representations like "binary"?

**Comment by leonuetzel** [comment]
I thought about having a number in Qm.n-Form and let it display as Decimals. So for example if i have the binary 0x01F0F0F0 as  signed Q8.24, then it should show me 1.941176414489746. If the same Value is a signed Q16.16 Number, then it should show 496.941162109375.

**Comment by flandreas** [comment]
Okay, I didn't know this format. I will look at it and see if I can implement it.

**Comment by leonuetzel** [comment]
https://chummersone.github.io/qformat.html
https://en.wikipedia.org/wiki/Q_(number_format)
