### ISSUE TITLE
Arbitrary Bitwidth for IO (and params)

### ISSUE THREAD

**Issue by daniel-endraws** [flandreas/antares#498]
I think it would be nice if I could input a number in. Currently if I put `11` in the expression tab, it doesn't show the bitwidth in the editor. Thanks!

**Comment by flandreas** [comment]
@daniel-endraws Thank you for your input.

Antares currently supports only certain predefined bit widths, i.e. the one suggested in the dropdown menu. 11 is not among them. The reason for this is that it was easier this way to implement IO views based on nibbles and the "Fan out" property of splitters/combiners.

If you enter the constant 11 as a bit width expression, the expression is internally evaluated and rejected, because it doesn't resolve to a supported bit width. It is a bug that Antares doesn't say that this is a unsupported bit width. I will open a bug issue for this.

I understand the requirement, and I think it makes sense to support any number between 1 and 64. Accepted as feature request.

In the meantime, as a workaround, you could use the next larger available bit width and ignore the top bits.

**Comment by daniel-endraws** [comment]
Thanks for the quick response! It would also be nice if the fan out could be arbitrary divisions specified by some sort of params.

**Comment by daniel-endraws** [comment]
Sorry I think I accidentally closed the issue...

Thanks for the quick response!

**Comment by flandreas** [comment]
Never mind
