### ISSUE TITLE
Switch Propagation Delay not Applying

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#574]
I have the switch delay in preferences set to 1ns so I can time how long it takes to go from input to stable output, but no matter what I do it seams stuck at 1000ns. I have tried applying many different speeds, restarts, and even editing the config file itself. I am mainly using circuit pin inputs as my switch, but the digital switches also don't update their delays.

Side note, would there also be a way to allow this value to be 0 for such purposes? Most of the time I don't need/want the pin inputs themselves to have any delay.

**Comment by flandreas** [comment]
@Kitick That's a bug, thank you for reporting this.

The bug was creeping in while I merged the huge changes done for the upcoming "Analog Circuits" feature, a feature that's still hidden from users because it's not yet completed. I'll fix it with the next release.

The bug is such that the 1000 ns are hardcoded in the code, so I'm afraid there is not much you can do as a workaround.

When implementing the fix, I'll make sure that you can set the default in the user preferences to 0. I see the benefit of a 0 value for measuring the overall propagation delay of an entire circuit. But don't forget that the purpose of something like 1000 ns switch delay is necessary to give a circuit enough time to do its thing until the human user releases the pressed switch button, especially with moderate simulation speed.
