### ISSUE TITLE
Display & simulate circuits in web browsers

### ISSUE THREAD

**Issue by flandreas** [flandreas/antares#684]
This involves the following steps:

- Create an account in the upcoming Antares Web application
- Design your circuits with Antares Desktop (as usual)
- Login in Antares Desktop (authentication against your Antares Web account)
- Upload your project from Antares Desktop to Antares Web
- Build a web page (using a method of your choice) and include Antares circuits from your uploaded project. Antares circuits are integrated as HTML iframes.

The result will be something like ["Making Logic Gates from Transistors"](https://www.antarescircuit.io/gates-from-transistors/), with the difference that this is currently statically deployed by us, where as this new feature allows any user to publish her own circuits and integrate them in her own web pages.

**Comment by Hougaarden** [comment]
Sharing circuits should be simple so that even less experienced users can use it. I consider Antares a tool for learning, it should not become a toy for computer specialists and advanced programmers. It would also be interesting to experience the opinions of others and even be able to get help with problems. A moderator must provide oversight to settle disputes and remove trolls. Published circuits must be able to be used and downloaded by anyone who is logged in.
